-- SMODS.Joker {
--     key = "garble_of_doom_and_despair",
--     cost = 10,
--     rarity = 4,
--     atlas = "other_jokers",
--     pos = {x=1,y=2},
--     pools = {
--         ["ocstob"] = true,
--         ["all_junk"] = true
--     },
--     add_to_deck = function(self,card,from_debuff)
--         G.GAME.garbl = true
--     end,
--     remove_from_deck = function(self,card,from_debuff)
--         G.GAME.garbl = false
--     end,
--     update = function(self,card,dt)
--         card:set_debuff(false)
--     end
-- }