-- SMODS.Joker {
--     key = 'overcomplicated',
--     cost = 2,
--     rarity = 1,
--     unlocked = true,
--     discovered = true,

--     calculate = function(self,card,context)
--         if context.joker_main then
--             return {
--                 message = "+((8*(sqrt(4)+(6/3)))/((6/3)*2))-(3*(6/3)))/(((log2(16))*(e^(ln(7))))/4 Mult)",
--                 mult_mod = 4
--             }
--         end
--     end
-- }
--do not use