[manifest]
version = "0.0.1"
dump_lua = true
priority = 99999

# fuck the gray bg bro
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
elseif G.GAME.won then 
ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}
'''
position = "at"
payload = '''
elseif G.GAME.won and G.GAME.omegarush == nil then
ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}
elseif G.GAME.won and G.GAME.omegarush < 1 then
ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}
elseif G.GAME.round_resets.blind_choices.Boss == 'bl_fizz_bossrushomega' then
ease_background_colour{new_colour = G.C.OMEGARED, special_colour = G.C.OMEGABLACK, contrast = 2}
'''
match_indent = true


# omegarush bg
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then'''
position = "before"
payload = '''
elseif G.GAME.omegarush == 1 and G.GAME.has_isotypical ~= true then
    ease_background_colour{new_colour = G.C.OMEGAWHITE, special_colour = G.C.OMEGABLACK, tertiary_colour = G.C.BLACK, contrast = 3}
'''
match_indent = true

# reclusive bg
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then'''
position = "before"
payload = '''
elseif G.GAME.reclusive_vessel == true and G.GAME.has_isotypical ~= true  then
    ease_background_colour{new_colour = G.C.OMEGABLACK, special_colour = G.C.OMEGABLACK, tertiary_colour = G.C.NIGHTMARE_PURPLE, contrast = 2}
'''
match_indent = true

# steelwire / starspace gc
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then'''
position = "before"
payload = '''
elseif G.GAME.evil_steel == true or G.GAME.fizz_starspace_horny_hour == true and G.GAME.has_isotypical ~= true then
    ease_background_colour{new_colour = G.C.OMEGABLACK, special_colour = G.C.ISO_CRIMSON, tertiary_colour = G.C.RED, contrast = 2}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then'''
position = "before"
payload = '''
elseif G.GAME.has_isotypical then
    ease_background_colour{new_colour = G.C.ISO_LIGHT_PURPLE, special_colour = G.C.ISO_DARK_PURPLE, contrast = 2}
'''
match_indent = true