[manifest]
version = "0.0.1"
dump_lua = true
priority = 1000

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "DARK_EDITION = {0,0,0,1},"
position = "after"
payload = """
OMEGABLACK = HEX("000000"),
OMEGARED = HEX("ff0000"),
OMEGAWHITE = HEX("ffffff"),
NIGHTMARE_BLUE = HEX("0000ff"),
NIGHTMARE_PURPLE = HEX("800080"),
PASTEL_YELLOW = HEX("FFFC75"),
PINK = HEX("FFAAD9"),
ISO_LIGHT_PURPLE = HEX("df9aff"),
ISO_DARK_PURPLE = HEX("cf69ff"),
ISO_CRIMSON = HEX("870000"),
ISO_EX_RARE = HEX("ff00a7"),
"""
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "dark_edition = G.C.DARK_EDITION,"
position = "after"
payload = """
iso_omegablack = G.C.OMEGABLACK,
iso_omegared = G.C.OMEGARED,
iso_omegawhite = G.C.OMEGAWHITE,
iso_nightmare_blue = G.C.NIGHTMARE_BLUE,
iso_nightmare_purple = G.C.NIGHTMARE_PURPLE,
pastel_yellow = G.C.PASTEL_YELLOW,
pink = G.C.PINK,
iso_light_purple = G.C.ISO_LIGHT_PURPLE,
iso_dark_purple = G.C.ISO_DARK_PURPLE,
iso_crimson = G.C.ISO_CRIMSON,
iso_exrare = G.C.ISO_EX_RARE,
"""
match_indent = true